apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-foundation
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
automountServiceAccountToken: false
