"""Premarket Intelligence — Watchlist, Catalyst, Gap, Scoring, Morning Briefing."""

from __future__ import annotations

from app.premarket.catalyst import (
    ORDERING_POLICY_KNOWN_AT_ASC_EVENT_TIME_ASC_TYPE_ASC_INSTRUMENT_KEY_ASC_ID_ASC,
    UNLINKED_INSTRUMENT_KEY_SENTINEL,
    CatalystClassificationRule,
    CatalystCollection,
    CatalystConfig,
    CatalystNormalizationRequest,
    CatalystProvenance,
    CatalystRecord,
    build_catalyst_record_id,
    catalyst_sort_key,
    coerce_news_events,
    declared_source_identity,
    normalize_catalysts,
    normalize_catalysts_from_parts,
)
from app.premarket.errors import (
    BriefingConflictError,
    BriefingDomainError,
    BriefingError,
    BriefingInvariantError,
    BriefingUnsupportedPolicyError,
    BriefingValidationError,
    CatalystClassificationError,
    CatalystError,
    CatalystIdentityConflictError,
    CatalystStaleKnownAtError,
    CatalystUnsupportedEventError,
    CatalystValidationError,
    GapAmbiguousSelectionError,
    GapDuplicateInstrumentError,
    GapError,
    GapMissingBarError,
    GapStaleKnownAtError,
    GapUnsupportedEventError,
    GapValidationError,
    GapZeroCloseError,
    PremarketDisabledError,
    PremarketError,
    ScoreConflictError,
    ScoreDomainError,
    ScoreDuplicateInstrumentError,
    ScoreError,
    ScoreInvariantError,
    ScoreStaleKnownAtError,
    ScoreUnsupportedPolicyError,
    ScoreValidationError,
    WatchlistDuplicateInstrumentError,
    WatchlistError,
    WatchlistUnsupportedCandidateError,
    WatchlistValidationError,
)
from app.premarket.gap import (
    GAP_DIRECTION_DOWN,
    GAP_DIRECTION_FLAT,
    GAP_DIRECTION_UP,
    GAP_PERCENT_QUANTIZE_POLICY_ID,
    ORDERING_POLICY_ABS_GAP_DESC_INSTRUMENT_KEY_ASC_ID_ASC,
    SELECTION_POLICY_TWO_BARS_BY_CLOSE_TIME_V1,
    GapCollection,
    GapConfig,
    GapProvenance,
    GapRecord,
    GapScanRequest,
    build_gap_record_id,
    coerce_bar_events,
    gap_sort_key,
    scan_gaps,
    scan_gaps_from_parts,
)
from app.premarket.morning_briefing import (
    DIGEST_METHOD_V1 as BRIEFING_DIGEST_METHOD_V1,
)
from app.premarket.morning_briefing import (
    IDENTITY_SPECIFICATION_V1 as BRIEFING_IDENTITY_SPECIFICATION_V1,
)
from app.premarket.morning_briefing import (
    ORDERING_PRESERVATION_POLICY_V1 as BRIEFING_ORDERING_PRESERVATION_POLICY_V1,
)
from app.premarket.morning_briefing import (
    POLICY_VERSION_V1 as BRIEFING_POLICY_VERSION_V1,
)
from app.premarket.morning_briefing import (
    PROVENANCE_SPECIFICATION_V1 as BRIEFING_PROVENANCE_SPECIFICATION_V1,
)
from app.premarket.morning_briefing import (
    BriefingCollection,
    BriefingConfig,
    BriefingProvenance,
    BriefingRecord,
    BriefingRequest,
    assemble_briefing,
    assemble_briefing_from_parts,
    reassemble,
)
from app.premarket.morning_briefing import (
    assert_replay_equal as assert_briefing_replay_equal,
)
from app.premarket.scoring import (
    ORDERING_POLICY_SCORE_DESC_INSTRUMENT_KEY_ASC_ID_ASC,
    POLICY_VERSION_V1,
    SCORE_QUANTIZE_POLICY_ID,
    WEIGHT_PROFILE_DEFAULT_V1,
    ScoreCollection,
    ScoreComponents,
    ScoreConfig,
    ScoreProvenance,
    ScoreRecord,
    ScoreRequest,
    assert_replay_equal,
    rescore,
    scan_scores,
    scan_scores_from_parts,
    score_sort_key,
)
from app.premarket.settings import PremarketSettings
from app.premarket.watchlist import (
    ORDERING_POLICY_RULE_PRIORITY_ASC_INSTRUMENT_KEY_ASC,
    Watchlist,
    WatchlistCandidate,
    WatchlistConfig,
    WatchlistEntry,
    WatchlistGenerationRequest,
    WatchlistInclusionRule,
    WatchlistProvenance,
    generate_watchlist,
    generate_watchlist_from_parts,
    normalize_candidate,
    normalize_candidates,
    watchlist_sort_key,
)

__all__ = [
    "BRIEFING_DIGEST_METHOD_V1",
    "BRIEFING_IDENTITY_SPECIFICATION_V1",
    "BRIEFING_ORDERING_PRESERVATION_POLICY_V1",
    "BRIEFING_POLICY_VERSION_V1",
    "BRIEFING_PROVENANCE_SPECIFICATION_V1",
    "GAP_DIRECTION_DOWN",
    "GAP_DIRECTION_FLAT",
    "GAP_DIRECTION_UP",
    "GAP_PERCENT_QUANTIZE_POLICY_ID",
    "ORDERING_POLICY_ABS_GAP_DESC_INSTRUMENT_KEY_ASC_ID_ASC",
    "ORDERING_POLICY_KNOWN_AT_ASC_EVENT_TIME_ASC_TYPE_ASC_INSTRUMENT_KEY_ASC_ID_ASC",
    "ORDERING_POLICY_RULE_PRIORITY_ASC_INSTRUMENT_KEY_ASC",
    "ORDERING_POLICY_SCORE_DESC_INSTRUMENT_KEY_ASC_ID_ASC",
    "POLICY_VERSION_V1",
    "SCORE_QUANTIZE_POLICY_ID",
    "SELECTION_POLICY_TWO_BARS_BY_CLOSE_TIME_V1",
    "UNLINKED_INSTRUMENT_KEY_SENTINEL",
    "WEIGHT_PROFILE_DEFAULT_V1",
    "BriefingCollection",
    "BriefingConfig",
    "BriefingConflictError",
    "BriefingDomainError",
    "BriefingError",
    "BriefingInvariantError",
    "BriefingProvenance",
    "BriefingRecord",
    "BriefingRequest",
    "BriefingUnsupportedPolicyError",
    "BriefingValidationError",
    "CatalystClassificationError",
    "CatalystClassificationRule",
    "CatalystCollection",
    "CatalystConfig",
    "CatalystError",
    "CatalystIdentityConflictError",
    "CatalystNormalizationRequest",
    "CatalystProvenance",
    "CatalystRecord",
    "CatalystStaleKnownAtError",
    "CatalystUnsupportedEventError",
    "CatalystValidationError",
    "GapAmbiguousSelectionError",
    "GapCollection",
    "GapConfig",
    "GapDuplicateInstrumentError",
    "GapError",
    "GapMissingBarError",
    "GapProvenance",
    "GapRecord",
    "GapScanRequest",
    "GapStaleKnownAtError",
    "GapUnsupportedEventError",
    "GapValidationError",
    "GapZeroCloseError",
    "PremarketDisabledError",
    "PremarketError",
    "PremarketSettings",
    "ScoreCollection",
    "ScoreComponents",
    "ScoreConfig",
    "ScoreConflictError",
    "ScoreDomainError",
    "ScoreDuplicateInstrumentError",
    "ScoreError",
    "ScoreInvariantError",
    "ScoreProvenance",
    "ScoreRecord",
    "ScoreRequest",
    "ScoreStaleKnownAtError",
    "ScoreUnsupportedPolicyError",
    "ScoreValidationError",
    "Watchlist",
    "WatchlistCandidate",
    "WatchlistConfig",
    "WatchlistDuplicateInstrumentError",
    "WatchlistEntry",
    "WatchlistError",
    "WatchlistGenerationRequest",
    "WatchlistInclusionRule",
    "WatchlistProvenance",
    "WatchlistUnsupportedCandidateError",
    "WatchlistValidationError",
    "assemble_briefing",
    "assemble_briefing_from_parts",
    "assert_briefing_replay_equal",
    "assert_replay_equal",
    "build_catalyst_record_id",
    "build_gap_record_id",
    "catalyst_sort_key",
    "coerce_bar_events",
    "coerce_news_events",
    "declared_source_identity",
    "gap_sort_key",
    "generate_watchlist",
    "generate_watchlist_from_parts",
    "normalize_candidate",
    "normalize_candidates",
    "normalize_catalysts",
    "normalize_catalysts_from_parts",
    "reassemble",
    "rescore",
    "scan_gaps",
    "scan_gaps_from_parts",
    "scan_scores",
    "scan_scores_from_parts",
    "score_sort_key",
    "watchlist_sort_key",
]
