apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: platform
  labels:
    app.kubernetes.io/part-of: platform-foundation
    bergama.io/secret-ref: "true"
type: Opaque
stringData:
  accessKey: "${SECRETREF:minio.accessKey}"
  secretKey: "${SECRETREF:minio.secretKey}"
