#!/usr/bin/env bash
# Close Sprint 1 on GitHub after `gh auth login`.
# Usage: bash scripts/github-close-sprint1.sh [owner/repo]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO="${1:-}"
PATH="${HOME}/.local/bin:${PATH}"
export PATH

command -v gh >/dev/null || { echo "Install gh: https://cli.github.com"; exit 1; }
gh auth status >/dev/null || { echo "Run: gh auth login"; exit 1; }

cd "${ROOT}"

if [[ -z "${REPO}" ]]; then
  REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
fi
if [[ -z "${REPO}" ]]; then
  read -r -p "GitHub owner/repo (e.g. enesdedeler/BergamaTrading): " REPO
fi

if ! git remote get-url origin >/dev/null 2>&1; then
  gh repo set-default "${REPO}" 2>/dev/null || true
  git remote add origin "https://github.com/${REPO}.git"
fi

git push -u origin main
git push -u origin feature/sprint1-gate
git push origin v0.1.0-sprint1

PR_URL="$(gh pr create \
  --base main \
  --head feature/sprint1-gate \
  --title "Sprint 1: Infrastructure foundation gate (v0.1.0-sprint1)" \
  --body "$(cat <<EOF
## Summary
- Sprint 1 infrastructure foundation gate with live Kind runtime evidence
- Version locks, secrets validation, backup/restore smoke, platform validation, Syft SBOM release
- Kind bootstrap + deploy targets; \`make gate-sprint1\` PASS (GO for Sprint 2)

## Release
- Tag: \`v0.1.0-sprint1\`
- Notes: \`releases/sprint-1/release-notes.md\`
- Changelog: \`CHANGELOG.md\`
- Retrospective: \`docs/sprints/sprint-1/retrospective.md\`

## Test plan
- [x] \`make gate-sprint1\` (live Kind)
- [x] \`make test-sprint1\` (12 tests)
- [x] Release SBOM generated by Syft

## Gate decision
**GO for Sprint 2**
EOF
)" 2>/dev/null || gh pr view --json url -q .url)"

echo "PR: ${PR_URL}"
gh pr merge --merge --delete-branch "${PR_URL##*/}" 2>/dev/null || echo "Merge PR manually after review"

# Milestone
MILESTONE_NUM="$(gh api repos/"${REPO}"/milestones --jq '.[] | select(.title=="Sprint 1") | .number' 2>/dev/null | head -1 || true)"
if [[ -z "${MILESTONE_NUM}" ]]; then
  MILESTONE_NUM="$(gh api repos/"${REPO}"/milestones -f title="Sprint 1" -f state="open" -f description="Infrastructure foundation gate" --jq .number)"
fi
gh api repos/"${REPO}"/milestones/"${MILESTONE_NUM}" -X PATCH -f state=closed >/dev/null
echo "Milestone Sprint 1 closed (#${MILESTONE_NUM})"

# GitHub Release
gh release create v0.1.0-sprint1 \
  --title "Sprint 1 — Infrastructure Foundation (v0.1.0-sprint1)" \
  --notes-file "${ROOT}/releases/sprint-1/release-notes.md" \
  --target feature/sprint1-gate

echo "GitHub release v0.1.0-sprint1 created"
