"""Frozen Intelligence Run productization version and outcome constants (WS1)."""

from __future__ import annotations

from app.intelligence_pipeline.policy import (
    FAILURE_DETAIL_MAX_LENGTH,
    GLOBAL_OUTCOME_FAMILIES,
    OUTCOME_ADMISSION_REJECTED,
    OUTCOME_COMPLETED_ADE_ABSTAIN,
    OUTCOME_COMPLETED_ADE_ACCEPT,
    OUTCOME_COMPLETED_DASHBOARD,
    OUTCOME_COMPLETED_HUMAN_REVIEW,
    OUTCOME_REQUIRED_STAGE_FAILED,
)

SNAPSHOT_CONTRACT_VERSION = "intelligence-run-productization.snapshot.v1"
PERSISTENCE_SCHEMA_VERSION = "intelligence-run-productization.persistence.v1"

PIPELINE_FINGERPRINT_LENGTH = 64
FAILURE_DETAIL_MAX_CHARS = FAILURE_DETAIL_MAX_LENGTH

PERSISTED_OUTCOMES: tuple[str, ...] = GLOBAL_OUTCOME_FAMILIES

assert PERSISTED_OUTCOMES == (
    OUTCOME_ADMISSION_REJECTED,
    OUTCOME_REQUIRED_STAGE_FAILED,
    OUTCOME_COMPLETED_DASHBOARD,
    OUTCOME_COMPLETED_HUMAN_REVIEW,
    OUTCOME_COMPLETED_ADE_ACCEPT,
    OUTCOME_COMPLETED_ADE_ABSTAIN,
)
